DATA:
  data_name: SUSTech1K
  data_root: dataset/SUSTech1K/SUSTech1K-Released-voxel.10temporal/tmp
  data_split: SUS
  frame_size: #not used with SUSTech1K
  class:
  feature: 1 #feature_size
  splits: ['train', '_000_', '_045_', '_090_', '_135_', '_180_', '_225_', '_270_', '_315_', '000-far', '090-near', '180-far', '270-far', '00-nm', '01-nm', 'bg', 'cl', 'cr', 'ub', 'uf', 'oc', 'nt']
  splits_variance: ['00-nm', '01-nm', 'bg', 'cl', 'cr', 'ub', 'uf', 'oc', 'nt']
  splits_view: ['_000_', '_045_', '_090_', '_135_', '_180_', '_225_', '_270_', '_315_', '000-far', '090-near', '180-far', '270-far']
  target:
  lines:
  structure: LidarGait3D
  datatype: half #bf16

  reload_data: True
  identifier: T_ #prefix for parallel training
  with_depth: False
  use_gpu: True
  use_metric: True
  use_Aloss: True #set to False to use metric learning only
  free_memory_required: 1024
  load_checkpoint: False #set to False to start a new trial
  checkpoint_timestamp: '2024-02-02 07:21:51.009417'

  visual: False
  visual_freq: 20
  visual_test_names: ['01-nm_090_0223', '01-bg_090_0013', '01-cl_090_0400', '00-nm_090_0400', '01-cr_090_0110', '01-ub_090_0333', '00-nm_090_0400']
  visual_train_names: ['01-ub_090_0301', '00-nm_090_0301']

TRAIN:
  ignore_label: None
  train_gpu: [0]
  workers: 8  # data loader workers
  batch_size: 8 # batch size for training
  batch_size_test: 64
  base_lr: 0.1
  epochs: 100
  start_epoch: 0
  step_epoch: 30
  momentum: 0.9
  weight_decay: 0.0005
  manual_seed: 7777
  print_freq: 1
  save_freq: 1
  save_path:
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  eval_freq: 1
  eval_start: 0.9
  mean_range: 50
Distributed: 
  dist_url: tcp://localhost:8888
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0

